[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GWDALI"
authors = [{name = "Josiel Mendonça Soares de Souza", email = "josiel.jms7@gmail.com"}]
dynamic = ["version", "description"]
